### ISSUE TITLE
On collection install, install  run-time dependencies from meta/main.yml for each included role.

### ISSUE THREAD

**Issue by chouseknecht** [ansible/mazer#137]
After installing an Ansible Collection:
 - traverse the `roles` directory, and for each role, install any dependencies enumerated in `meta/main.yml`.

**Comment by alikins** [comment]
Part 2 ("After installing a traditional Ansible role, Install any dependencies enumerated in meta/main.yml") is implemented via:
https://github.com/ansible/mazer/pull/156
https://github.com/ansible/mazer/pull/158
https://github.com/ansible/mazer/pull/157

**Comment by alikins** [comment]
Part 1 ("After installing an Ansible Collection, traverse the roles directory, and for each role, install any dependencies enumerated in meta/main.yml."). This bug list two parts, but going to consider part2 here as split out into https://github.com/ansible/mazer/issues/138

This is not implemented currently as of (~0.3.0, 5ea70d3cd44c660c8aa46a5217368dcdbc2fd8c6).

I'm not sure if it doing a transverse down into all of the roles looking for deps is consistent with the idea that a collection is the installable unit. 
 - Dependencies specified in a roles meta/main.yml are going to be a dep that points to another role, not necessarily a collection. Granted, this is fuzzy for the case of traditional roles available in galaxy (where the role is also sort of a Collection).
- role meta/main.yml deps are runtime deps and not necessarily install time requirements. 
    -  a role inside of a collection could have a meta/main.yml dep on another role inside of the collection, which would not have a name that mazer could resolve but ansible-playbook could resolve it at runtime.
    - a role inside of a collection could have a dep on a role that is not known to mazer (a locally installed role, or a role provided outside of mazer/galaxy)
- All of the roles within a collection would need to share the same transitive requirements. ie, roles inside a collection could not have dependencies that conflict with each other since there would be no way to solve them all at the same time.

**Comment by alikins** [comment]
Removing part2 of original comment "After installing a traditional Ansible role: Install any dependencies enumerated in meta/main.yml" as it is split out into https://github.com/ansible/mazer/issues/138

**Comment by alikins** [comment]
WONTFIX in lieu of collection being the unit of installation and dependencies. Roles that need roles from other collections should update the containing collection dep.
